/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Book = IDL.Record({
  'id' : IDL.Nat32,
  'finalPrice' : IDL.Nat,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'author' : IDL.Text,
  'category' : IDL.Text,
  'stockAvailable' : IDL.Nat,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'bookId' : IDL.Nat32,
  'quantity' : IDL.Nat,
  'priceAtPurchase' : IDL.Nat,
});
export const BookOrder = IDL.Record({
  'status' : IDL.Text,
  'createdAt' : Time,
  'orderId' : IDL.Nat32,
  'buyerContact' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'buyerPrincipal' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'buyerName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBook' : IDL.Func([IDL.Nat32], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
  'getBook' : IDL.Func([IDL.Nat32], [Book], ['query']),
  'getBookStock' : IDL.Func([IDL.Nat32], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat32], [BookOrder], ['query']),
  'getOrdersByBuyer' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(OrderItem)], [], []),
  'restockBook' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBook' : IDL.Func([Book], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat32,
    'finalPrice' : IDL.Nat,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'author' : IDL.Text,
    'category' : IDL.Text,
    'stockAvailable' : IDL.Nat,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'bookId' : IDL.Nat32,
    'quantity' : IDL.Nat,
    'priceAtPurchase' : IDL.Nat,
  });
  const BookOrder = IDL.Record({
    'status' : IDL.Text,
    'createdAt' : Time,
    'orderId' : IDL.Nat32,
    'buyerContact' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'buyerPrincipal' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'buyerName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'contact' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBook' : IDL.Func([IDL.Nat32], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
    'getBook' : IDL.Func([IDL.Nat32], [Book], ['query']),
    'getBookStock' : IDL.Func([IDL.Nat32], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat32], [BookOrder], ['query']),
    'getOrdersByBuyer' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(OrderItem)], [], []),
    'restockBook' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBook' : IDL.Func([Book], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat32, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };