/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : number,
  'finalPrice' : bigint,
  'coverImageUrl' : string,
  'title' : string,
  'originalPrice' : bigint,
  'description' : string,
  'discountPercent' : bigint,
  'author' : string,
  'category' : string,
  'stockAvailable' : bigint,
}
export interface BookOrder {
  'status' : string,
  'createdAt' : Time,
  'orderId' : number,
  'buyerContact' : string,
  'totalAmount' : bigint,
  'buyerPrincipal' : Principal,
  'items' : Array<OrderItem>,
  'buyerName' : string,
}
export interface OrderItem {
  'bookId' : number,
  'quantity' : bigint,
  'priceAtPurchase' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'contact' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBook' : ActorMethod<[number], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllOrders' : ActorMethod<[], Array<BookOrder>>,
  'getBook' : ActorMethod<[number], Book>,
  'getBookStock' : ActorMethod<[number], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[number], BookOrder>,
  'getOrdersByBuyer' : ActorMethod<[], Array<BookOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderItem>], undefined>,
  'restockBook' : ActorMethod<[number, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBook' : ActorMethod<[Book], undefined>,
  'updateOrderStatus' : ActorMethod<[number, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];