/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookCategory = IDL.Variant({
  'Journals' : IDL.Null,
  'BareActs' : IDL.Null,
  'AcademicBooks' : IDL.Null,
  'ProfessionalBooks' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Book = IDL.Record({
  'id' : IDL.Nat32,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'yearPublished' : IDL.Nat,
  'publisher' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'author' : IDL.Text,
  'originalPriceINR' : IDL.Nat,
  'numPages' : IDL.Nat,
  'finalPriceINR' : IDL.Nat,
  'category' : BookCategory,
  'stockAvailable' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const DeliveryInfo = IDL.Record({
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'comments' : IDL.Opt(IDL.Text),
  'companyAddress' : IDL.Text,
});
export const StatusChangeEntry = IDL.Record({
  'changedBy' : IDL.Principal,
  'timestamp' : Time,
  'newStatus' : OrderStatus,
});
export const OrderItem = IDL.Record({
  'priceAtPurchaseINR' : IDL.Nat,
  'bookId' : IDL.Nat32,
  'quantity' : IDL.Nat,
});
export const BookOrder = IDL.Record({
  'status' : OrderStatus,
  'createdAt' : Time,
  'deliveryInfo' : DeliveryInfo,
  'statusHistory' : IDL.Vec(StatusChangeEntry),
  'orderId' : IDL.Nat32,
  'buyerContact' : IDL.Text,
  'totalAmountINR' : IDL.Nat,
  'buyerPrincipal' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'buyerName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        BookCategory,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBook' : IDL.Func([IDL.Nat32], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
  'getBook' : IDL.Func([IDL.Nat32], [Book], ['query']),
  'getBookStock' : IDL.Func([IDL.Nat32], [IDL.Nat], ['query']),
  'getBooksByCategory' : IDL.Func([BookCategory], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat32], [BookOrder], ['query']),
  'getOrderStatusHistory' : IDL.Func(
      [IDL.Nat32],
      [IDL.Vec(StatusChangeEntry)],
      ['query'],
    ),
  'getOrdersByBuyer' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, DeliveryInfo, IDL.Vec(OrderItem)],
      [],
      [],
    ),
  'restockBook' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBook' : IDL.Func([Book], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat32, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookCategory = IDL.Variant({
    'Journals' : IDL.Null,
    'BareActs' : IDL.Null,
    'AcademicBooks' : IDL.Null,
    'ProfessionalBooks' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Book = IDL.Record({
    'id' : IDL.Nat32,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'yearPublished' : IDL.Nat,
    'publisher' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'author' : IDL.Text,
    'originalPriceINR' : IDL.Nat,
    'numPages' : IDL.Nat,
    'finalPriceINR' : IDL.Nat,
    'category' : BookCategory,
    'stockAvailable' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const DeliveryInfo = IDL.Record({
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'comments' : IDL.Opt(IDL.Text),
    'companyAddress' : IDL.Text,
  });
  const StatusChangeEntry = IDL.Record({
    'changedBy' : IDL.Principal,
    'timestamp' : Time,
    'newStatus' : OrderStatus,
  });
  const OrderItem = IDL.Record({
    'priceAtPurchaseINR' : IDL.Nat,
    'bookId' : IDL.Nat32,
    'quantity' : IDL.Nat,
  });
  const BookOrder = IDL.Record({
    'status' : OrderStatus,
    'createdAt' : Time,
    'deliveryInfo' : DeliveryInfo,
    'statusHistory' : IDL.Vec(StatusChangeEntry),
    'orderId' : IDL.Nat32,
    'buyerContact' : IDL.Text,
    'totalAmountINR' : IDL.Nat,
    'buyerPrincipal' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'buyerName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'contact' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          BookCategory,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBook' : IDL.Func([IDL.Nat32], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
    'getBook' : IDL.Func([IDL.Nat32], [Book], ['query']),
    'getBookStock' : IDL.Func([IDL.Nat32], [IDL.Nat], ['query']),
    'getBooksByCategory' : IDL.Func([BookCategory], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat32], [BookOrder], ['query']),
    'getOrderStatusHistory' : IDL.Func(
        [IDL.Nat32],
        [IDL.Vec(StatusChangeEntry)],
        ['query'],
      ),
    'getOrdersByBuyer' : IDL.Func([], [IDL.Vec(BookOrder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, DeliveryInfo, IDL.Vec(OrderItem)],
        [],
        [],
      ),
    'restockBook' : IDL.Func([IDL.Nat32, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBook' : IDL.Func([Book], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat32, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };